package com.company;

public class Main {

    public static void main(String[] args) {
        String ANSI_BLACK = "\u001B[30m";
        String ANSI_RED = "\u001B[31m";
        String ANSI_GREEN = "\u001B[32m";
        String ANSI_YELLOW = "\u001B[33m";
        String ANSI_BLUE = "\u001B[34m";
        String ANSI_PURPLE = "\u001B[35m";
        String ANSI_CYAN = "\u001B[36m";
        String ANSI_WHITE = "\u001B[37m";


        char Pixel = '\u2587';
        System.out.println(ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel);
        System.out.println(ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel);
        System.out.println(ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel);
        System.out.println(ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_BLACK + Pixel + ANSI_BLACK + Pixel + ANSI_BLACK + Pixel + ANSI_BLACK + Pixel + ANSI_BLACK + Pixel + ANSI_BLACK + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel);
        System.out.println(ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_BLACK + Pixel + ANSI_BLACK + Pixel + ANSI_RED + Pixel + ANSI_RED + Pixel + ANSI_RED + Pixel + ANSI_RED + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_BLACK + Pixel + ANSI_BLACK + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel);
        System.out.println(ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_BLACK + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_RED + Pixel + ANSI_RED + Pixel + ANSI_RED + Pixel + ANSI_RED + Pixel + ANSI_RED + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_BLACK + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel);
        System.out.println(ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_BLACK + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_RED + Pixel + ANSI_RED + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_RED + Pixel + ANSI_RED + Pixel + ANSI_RED + Pixel + ANSI_RED + Pixel + ANSI_RED + Pixel + ANSI_RED + Pixel + ANSI_BLACK + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel + ANSI_WHITE + Pixel);
        System.out.println(ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_BLACK + Pixel +ANSI_RED + Pixel +ANSI_RED + Pixel +ANSI_RED + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_RED + Pixel +ANSI_RED + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_RED + Pixel +ANSI_BLACK + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel );
        System.out.println(ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_BLACK + Pixel + ANSI_WHITE + Pixel +ANSI_RED + Pixel +ANSI_RED + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel + ANSI_RED + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_BLACK + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel +ANSI_WHITE + Pixel );
    }
}
